[package]
name = "treasury"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "ArenaX DAO treasury management contract"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk.workspace = true
time-lock = { path = "../time-lock" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
